name: Process and Upload Shopify CSV to GCS

on:
  schedule:
    # Runs at 00:00 UTC daily
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pandas numpy requests google-cloud-storage

      - name: Write GCS credentials file
        run: |
          echo "${{ secrets.GCS_CREDENTIALS }}" > gcs_credentials.json

      - name: Run processing script and upload file
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcs_credentials.json
        run: |
          python your_script.py
